version: '3'
services:
  producer1:
    container_name: kafka_producer_1_2_1
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "1 500 250"

  producer2:
    container_name: kafka_producer_1_2_2
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "1 500 250"
      
networks:
  kafka:
    name: kafka
    external: true
    