version: '3'
services:
  producer:
    container_name: activemq_producer_1_1_1
    build: 
      context: "../../../../src/activemq/Producer/Producer.ActiveMQ"
      dockerfile: Dockerfile
    networks:
      - activemq
    command: "1 1000 256000"
      
networks:
  activemq:
    name: activemq
    external: true
    