version: '3'
services:
  producer:
    container_name: activemq_producer_4_1_1
    build: 
      context: "../../../../src/activemq/Producer/Producer.ActiveMQ"
      dockerfile: Dockerfile
    networks:
      - activemq
    command: "4 500000000 1000000"
      
networks:
  activemq:
    name: activemq
    external: true
    