version: '3'
services:
  producer1:
    container_name: kafka_producer_3_4_1
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "5 500000000 256000"

  producer2:
    container_name: kafka_producer_3_4_2
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "5 500000000 256000"
      
networks:
  kafka:
    name: kafka
    external: true
    