version: '3'
services:
  consumer:
    container_name: kafka_consumer_1_2_1
    build: 
      context: "../../../../src/kafka/Consumer/Consumer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "1"
      
networks:
  kafka:
    name: kafka
    external: true
    