version: '3'
services:
  producer1:
    container_name: producer_4_2_1
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "4 250000000 true 1000000"
  
  producer2:
    container_name: producer_4_2_2
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "4 250000000 true 1000000"
      
networks:
  rabbit:
    name: rabbit
    external: true
    