version: '3'
services:
  producer:
    container_name: kafka_producer_4_3_1
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "6 500000000 1000000"
      
networks:
  kafka:
    name: kafka
    external: true
    