version: '3'
services:
  producer:
    container_name: rabbitmq_producer_3_1_1
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "3 2000000000 1000000 true"
      
networks:
  rabbit:
    name: rabbit
    external: true
    