version: '3'
services:
  producer:
    container_name: producer_2_3_1
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "2 20000 true" #20 seconds and producer sends message throught the fanout exchange
      
networks:
  rabbit:
    name: rabbit
    external: true
    