version: '3'
services:
  consumer1:
    container_name: consumer_4_4_1
    build: 
      context: "../../../../src/rabbitmq/Consumer/Consumer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "5"
  
  consumer2:
    container_name: consumer_4_4_2
    build: 
      context: "../../../../src/rabbitmq/Consumer/Consumer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "5"

networks:
  rabbit:
    name: rabbit
    external: true
    