version: '3'
services:
  producer:
    container_name: producer_3_1_1
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "3 1000000000 true" #1 GB and producer sends message throught the fanout exchange
      
networks:
  rabbit:
    name: rabbit
    external: true
    