version: '3'
services:
  producer1:
    container_name: producer_3_2_1
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "3 500000000 true" #1 GB and producer sends message throught the fanout exchange
  
  producer2:
    container_name: producer_3_2_2
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "3 500000000 false" #1 GB and producer does not send message throught the fanout exchange
      
networks:
  rabbit:
    name: rabbit
    external: true
    