version: '3'
services:
  producer1:
    container_name: activemq_producer_1_2_1
    build: 
      context: "../../../../src/activemq/Producer/Producer.ActiveMQ"
      dockerfile: Dockerfile
    networks:
      - activemq
    command: "1 500 1000000"

  producer2:
    container_name: activemq_producer_1_2_2
    build: 
      context: "../../../../src/activemq/Producer/Producer.ActiveMQ"
      dockerfile: Dockerfile
    networks:
      - activemq
    command: "1 500 1000000"
      
networks:
  activemq:
    name: activemq
    external: true
    