version: '3'
services:
  producer:
    container_name: producer_4_3_1
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "4 1000000000 true" # 1GB packet and producer sends message throught the fanout exchange
      
networks:
  rabbit:
    name: rabbit
    external: true
    