version: '3'
services:
  producer1:
    container_name: kafka_producer_4_2_1
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "4 250000000 1000000"

  producer2:
    container_name: kafka_producer_4_2_2
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "4 250000000 1000000"
      
networks:
  kafka:
    name: kafka
    external: true
    