version: '3'
services:
  consumer:
    container_name: consumer_1_1_1
    build: 
      context: "../../../../src/rabbitmq/Consumer/Consumer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "1"
      
networks:
  rabbit:
    name: rabbit
    external: true
    