version: '3'
services:
  producer1:
    container_name: producer_2_2_1
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "2 20000 true" #20 seconds messages and producer sends message throught the fanout exchange
  
  producer2:
    container_name: producer_2_2_2
    build: 
      context: "../../../../src/rabbitmq/Producer/Producer.RabbitMQ"
      dockerfile: Dockerfile
    networks:
      - rabbit
    command: "2 20000 false" #20 seconds and producer does not send message throught the fanout exchange
      
networks:
  rabbit:
    name: rabbit
    external: true
    