version: '3'
services:
  producer:
    container_name: kafka_producer_1_1_1
    build: 
      context: "../../../../src/kafka/Producer/Producer.Kafka"
      dockerfile: Dockerfile
    networks:
      - kafka
    command: "1 10000 " #10000 messages
      
networks:
  kafka:
    name: kafka
    external: true
    